config/routes.rb
Surgconf::Application.routes.draw do
  root              to: 'static_pages#home'
  resources         :users
  resources         :patients
  resources         :sessions, only: [:new, :create, :destroy]
  resources         :conferences
  resources         :appearances

  match '/help',    to: 'static_pages#help', via: [:get, :post]
  match '/signup',   to: 'users#new', via: [:get, :post]
  match '/signout',  to: 'sessions#destroy', via: :delete
  match '/signin',   to: 'sessions#new', via: [:get, :post]

end

app/models/conference.rb
class Conference < ActiveRecord::Base
  attr_accessible :conf_date, :appearances_attributes
  validates :conf_date, presence: true

  has_many :appearances
  accepts_nested_attributes_for :appearances, allow_destroy: true
  has_many :patients, through: :appearances

  def patients_not_held
    # Return a list of patients _not_ in this conference if any are present
    if Patient.where(["id NOT IN(?)", appearances.map(&:patient_id)]).any?
      Patient.where(["id NOT IN(?)", appearances.map(&:patient_id)]).order("surname ASC")
    # If this conference does indeed contain patients return an empty array
    elsif self.patients.any?
      Array.new
    # If No Patients in Conference AND none elsewhere then return All patients.
    else
      Patient.all(order: "surname ASC")
    end
  end
end

# == Schema Information
#
# Table name: conferences
#
#  id         :integer         not null, primary key
#  conf_date  :date
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_filter :signed_in_user,
                only: [:index, :new, :edit, :update, :destroy, :show]
  before_filter :editor_user, only: [:new, :create, :update, :edit]
  before_filter :viewer_user, only: [:index]
  before_filter :admin_user,     only: :destroy

  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all(order: 'conf_date DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conferences }
    end
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
    @conference = Conference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/new
  # GET /conferences/new.json
  def new
    @conference = Conference.create(conf_date: Date.today)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/1/edit
  def edit
    @conference = Conference.find(params[:id])
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(params[:conference])

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render json: @conference, status: :created, location: @conference }
      else
        format.html { render action: "new" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conferences/1
  # PUT /conferences/1.json
  def update
    @conference = Conference.find(params[:id])

    respond_to do |format|
      if @conference.update_attributes(params[:conference])
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference = Conference.find(params[:id])
    @conference.destroy

    respond_to do |format|
      format.html { redirect_to conferences_url }
      format.json { head :no_content }
    end
  end


  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      if !current_user.editor?
        flash[:error] = "You are not an administrator."
        redirect_to current_user
      end
    end

    def editor_user
      if !current_user.editor?
        flash[:error] = "You do not have conference editing privileges."
        redirect_to current_user
      end
    end

    def viewer_user
      if !current_user.viewer?
        flash[:error] = "You do not yet have conference viewing privileges."
        redirect_to current_user
      end
    end
end

app/helpers/conferences_helper.rb
module ConferencesHelper

  

end

app/views/conferences/_conference_patient_table.html.erb
<td><%= link_to "#{patient.mrn}", patient_path(patient) %></td>
<td><%= patient.surname %></td>
<td><%= patient.firstname %></td>
<td><%= patient.dob %></td>
<td><%= patient.diagnosis %></td>
<td>Attending Here</td>

app/views/conferences/_edit_conference_patient_table.html.erb
<% if goal == 'add' %>
  <td><%= button_to "Add", {:controller => :appearances, :action => 'create', :conf_id => @conference.id,
    :pat_id => patient.id}, method: :create, class: "btn btn-success btn-mini" %></td>
<% else %>

  <td><%= button_to "Rem", {:controller => :appearances, :action => 'destroy', 
    :id => @conference.appearances.where(patient_id: patient.id).map(&:id)}, method: :delete, class: "btn btn-warning btn-mini" %></td>

<% end %>
<td><%= link_to "#{patient.mrn}", patient_path(patient) %></td>
<td><%= patient.surname %></td>
<td><%= patient.firstname %></td>
<td><%= patient.dob %></td>
<td><%= patient.diagnosis %></td>
<td>Attending Here</td>

app/views/conferences/_form.html.haml
= form_for @conference do |f|
  -if @conference.errors.any?
    #error_explanation
      %h2= "#{pluralize(@conference.errors.count, "error")} prohibited this conference from being saved:"
      %ul
        - @conference.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.date_select :conf_date
  .actions
    = f.submit 'Save'
  :erb
    <div>
      <div class="span12">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Remove</th>
            <th>MRN</th>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Date of Birth</th>
            <th>Diagnosis</th>
            <th>Primary Attending</th>
          </tr>
        </thead>
        <tbody>
          <% @conference.patients.each do |patient| %>
            <tr>
              <%= render partial: 'edit_conference_patient_table', :locals => {:goal => 'remove', patient: patient} %>
            </tr>
          <% end %>
         
        </tbody>
      </table>
      </div>
    </div>

    <div class="span12">
    <h2 class="center"><small>Add Patients to Conference Schedule</small></h2>
    <div class="span11">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <td>Add</th>
            <th>MRN</th>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Date of Birth</th>
            <th>Diagnosis</th>
            <th>Primary Attending</th>
          </tr>
        </thead>
        <tbody>
          <% @conference.patients_not_held.each do |patient| %>
            <tr>
              <%= render partial: 'edit_conference_patient_table', :locals => {:goal => 'add', patient: patient}  %>
            </tr>
          <% end %>
         
        </tbody>
      </table>
    </div>
    </div>

app/views/conferences/edit.html.haml
%h1 Editing conference

= render 'form'

= link_to 'Show', @conference
\|
= link_to 'Back', conferences_path

app/views/conferences/index.html.erb
<%= provide(:title, 'Available Conferences') %> 
<div class="page-header center">
  <h1>Available Conferences</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Conference Date</th>
      <th>Number of Patients</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @conferences.each do |conf| %>
      <tr>
        <td width="20%"><%= link_to pretty_date_with_year(conf.conf_date), conf %></td>
        <td width="10%"><center>
          <% count = conf.patients.count %>
          <% if count > 3 %>
            <span class="badge badge-important">
              <%= conf.patients.count %>
            </span>
          <% elsif count == 3 %>
            <span class="badge badge-warning">
              <%= conf.patients.count %>
            </span>
          <% elsif count == 2 %>
            <span class="badge badge-success">
              <%= conf.patients.count %>
            </span>
          <% elsif count == 1 %>
            <span class="badge badge-info">
              <%= conf.patients.count %>
            </span>
          <% else %>
            <span class="badge">
              <%= conf.patients.count %>
            </span>
          <% end %>
        </center>
        </td>
        <td width="70%">
          <ul style="list-style-type: none;">
          <% conf.patients.order('surname ASC').each do |pat| %>
            <li style="display: inline; border-radius: 15px; padding: .2em 1em; background-color: #E8E7E3"><%= "#{pat.surname}" %></li>
          <% end %>
          </div>
        </td>
      </tr>
    <% end %> 
  </tbody>
</table>
</ul>

app/views/conferences/new.html.haml
%h1 New conference

= render 'form'

= link_to 'Back', conferences_path

app/views/conferences/show.html.erb
<%= provide(:title, 'Conference Listing') %> 
<div class="page-header center">
  <h1>Conference Listing<br/><small><%= @conference.conf_date %></small></h1>
</div>

<div class="span4">
<%= link_to raw('<i class="icon-circle-arrow-left icon-black"></i> Conferences'), conferences_path, class: "btn btn-action" %>
</div>

<br/><br/>
<div class="span11">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>MRN</th>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Date of Birth</th>
        <th>Diagnosis</th>
        <th>Primary Attending</th>
      </tr>
    </thead>
    <tbody>
      <% @conference.patients.each do |patient| %>
        <tr>
          <%= render partial: 'conference_patient_table', :locals => {:goal => 'remove', patient: patient} %>
        </tr>
      <% end %>
     
    </tbody>
  </table>
</div>

<div class="span4">
  <% if current_user.editor? %>
    <%= link_to raw('<i class="icon-pencil icon-black"></i> Edit'), edit_conference_path, class: "btn btn-action" %>
  <% end %>
  <% if current_user.admin? %>
    <%= link_to "Delete Conference", @conference, class: "btn btn-danger", method: :delete, confirm: "Really Delete This Conference Forever?" %>
  <% end %>
</div>