config/routes.rb
Surgconf::Application.routes.draw do
  root              to: 'static_pages#home'
  resources         :users
  resources         :patients
  resources         :sessions, only: [:new, :create, :destroy]
  resources         :conferences
  resources         :appearances

  match '/help',    to: 'static_pages#help', via: [:get, :post]
  match '/signup',   to: 'users#new', via: [:get, :post]
  match '/signout',  to: 'sessions#destroy', via: :delete
  match '/signin',   to: 'sessions#new', via: [:get, :post]

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :surname, :firstname, :mrn, :dob 
  attr_accessible :pmhx, :rx, :vitals
  attr_accessible :cath, :diagnosis, :echo, :ekg, :exam, :other 
  attr_accessible :summary, :decisions

  validates :surname, :firstname, presence: true, length: { maximum: 30 }
  validates :mrn, presence: true, uniqueness: { case_sensitive: false }
  validates :dob, presence: true

  has_many :appearances
  has_many :conferences, through: :appearances

end

# == Schema Information
#
# Table name: patients
#
#  id         :integer         not null, primary key
#  surname    :string(255)
#  firstname  :string(255)
#  dob        :date
#  mrn        :string(255)
#  diagnosis  :string(255)
#  pmhx       :text
#  rx         :text
#  vitals     :text
#  exam       :text
#  ekg        :text
#  echo       :text
#  cath       :text
#  other      :text
#  summary    :text
#  decisions  :text
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :signed_in_user,
                only: [:index, :new, :edit, :update, :destroy, :show]
  before_filter :editor_user, only: [:new, :create, :update, :edit]
  before_filter :viewer_user, only: [:index]
  before_filter :admin_user,     only: :destroy

  def index
    @patients = Patient.all(order: 'surname, firstname')
  end

  def new
    @patient = Patient.new
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def create
    @patient = Patient.new(params[:patient])
    if @patient.save
      flash[:success] = "Patient #{@patient.firstname} #{@patient.surname} saved..."
      redirect_to patients_path
    else
      render 'new'
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update_attributes(params[:patient])
      flash[:success] = "Patient updated"
      redirect_to @patient
    else
      render 'edit'
    end
  end

  def destroy
    Patient.find(params[:id]).destroy
    redirect_to patients_path, flash[:success] = "Patient destroyed"
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      if !current_user.editor?
        flash[:error] = "You are not an administrator."
        redirect_to current_user
      end
    end

    def editor_user
      if !current_user.editor?
        flash[:error] = "You do not have patient editing privileges."
        redirect_to current_user
      end
    end

    def viewer_user
      if !current_user.viewer?
        flash[:error] = "You do not yet have patient viewing privileges."
        redirect_to current_user
      end
    end

end

app/helpers/patient_helper.rb
module PatientHelper

  def linecount(field)
    [@patient[field].lines.count+1,3].max  
  end

  def empty_field
    
  end

	def proper_name(field)
    name = {pmhx: "Past Medical History",
            rx: "Medications",
            vitals: "Recent Vitals",
            exam: "Exam",
            ekg: "EKGs",
            echo: "Echocardiograms",
            cath: "Catheterizations",
            other: "Other Tests",
            summary: "Summary",

            surname: "Last Name",
            firstname: "First Name",
            mrn: "MRN",
            dob: "Date of Birth",
            diagnosis: "Primary Diagnosis"}
    name[field]
  end

end

app/views/patients/_patienttable.html.erb
<td><%= link_to "#{patient.mrn}", patient_path(patient) %></td>
<td><%= patient.surname %></td>
<td><%= patient.firstname %></td>
<td><%= patient.diagnosis %></td>
<td><%= pretty_date patient.created_at %></td>
<td><%= pretty_date patient.updated_at %></td>

app/views/patients/edit.html.erb
<%= provide(:title, 'Edit Patient') %> 
<h1>Edit Patient</h1>
  <div>
      <%= form_for @patient, html: {class: "well form-horizontal"} do |f| %>
        <table class="table table-bordered table-striped">
          <thead>
            <tr>
              <% %w{surname firstname mrn dob diagnosis}.each do |field| %>
                <th>
                <%= proper_name(field.to_sym) %><br/>
                <%= f.text_field field, class: "input-medium" %>
                </th>
              <% end %>
            </tr>
          </thead>

          <tbody>
            <% %w{pmhx rx vitals exam ekg echo cath other summary}.each do |field| %>
              <tr>
                <td colspan=5>  
                  <%= proper_name(field.to_sym) %>
                  <%= f.text_area field, class: "span12", rows: linecount(field) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= f.submit "Save Patient", class: "btn btn-large btn-primary" %>
      <% end %> <!-- End Form -->
  </div>

app/views/patients/index.html.erb
<%= provide(:title, 'All Patients') %> 
<h2><%= yield(:title) %></h2>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>MRN</th>
      <th>Surname</th>
      <th>Firstname</th>
      <th>Diagnosis</th>
      <th>Created</th>
      <th>Updated</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <%= render 'patienttable', patient: patient %>
      </tr>
    <% end %> 
  </tbody>
</table>
</ul>

app/views/patients/new.html.erb
<%= provide(:title, 'Create New Patient') %> 
<h1>Create New Patient</h1>
  <div class="container">
      <%= form_for @patient, html: {class: "well form-horizontal"} do |f| %>

        <% %w{surname firstname mrn dob diagnosis}.each do |field| %>
          <%= f.label field %>
          <%= f.text_field field, class: "span3" %>
        <% end %>

        <% %w{pmhx rx vitals exam ekg echo cath other summary decisions}.each do |field| %>
          <%= f.label field %>
          <%= f.text_area field, class: "span10", rows: "3" %>
        <% end %>

      <% end %> <!-- End Form -->
  </div>

<!-- <div class="control-group">
            <label class="control-label" for="textarea">Textarea</label>
            <div class="controls">
              <textarea class="input-xlarge" id="textarea" rows="3"></textarea>
            </div>
          </div> 

          <div class="container">
    <div class="row">
        <div class="span12">
            <form class="form-horizontal" method="post" action="/form/">
                <fieldset>
                    <legend>Please login</legend>
                    <div class="control-group">
                        <label class="control-label" for="id_username">Username</label>
                        <div class="controls">
                            <input name="username" maxlength="100" placeholder="Enter your username..." type="text" class="input-large" id="id_username" />
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="id_password">Password</label>
                        <div class="controls">
                            <input name="password" maxlength="100" placeholder="Enter your password..." type="password" class="input-large" id="id_password" />
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div> -->

app/views/patients/show.html.erb
<%= provide(:title, 'View Patient') %> 
<div class="page-header center">
  <h1><%= "#{@patient.firstname.capitalize} #{@patient.surname.capitalize}" %><br/>
    <small>Demographics and Facesheet</small>
  </h1>
  <%= link_to raw('<i class="icon-circle-arrow-left icon-black"></i> Back'), :back, class: "btn btn-action" %>

  <% if current_user.editor? %>
    <a class="btn btn-warning" href=<%= edit_patient_path %> >
      <i class="icon-pencil icon-white"></i> Edit This Patient</a>
  <% end %>
  
</div>

<div class="row-fluid">

  <div class="span4 well">
    <h2>Demographics</h2>
    <strong><h5><%= "#{@patient.surname}, #{@patient.firstname}" %></strong></h5><br/>
    <strong><h5><%= "DOB:" %></strong> <%= "#{@patient.dob}" %></h5><br/>
    <strong><h5><%= "MRN:" %></strong> <%= "#{@patient.mrn}" %></h5><br/>
    <strong><h5><%= "Diag:" %></strong> <%= "#{@patient.diagnosis}" %></h5>
  </div>

  <div class="span4">
    <h2>Extra</h2>
    <p></p>
  </div>

  <div class="span3">
    <h2>Presentations</h2>
    <ul>
      <% @patient.conferences.order('conf_date DESC').each do |conf| %>
        <li><%= link_to "#{pretty_date_with_year(conf.conf_date)}", conf %></li>
      <% end %>
    </ul>
  </div>
</div> <!-- row -->

<section id="patientinfo">
  <div class="patient=header">
    <h2>Patient Information</h2>
  </div>

  <table class="table">
    <body>
      <% %w{pmhx rx vitals exam ekg echo cath other summary}.each do |field| %>
        <tr>
          <% if @patient[field].blank? %>
            <td class="span2">
              <%= proper_name(field.to_sym) %>
            </td>
            <td class="span10"> 
              <i>This Field is Empty</i>
            </td>

          <% else %>
            <td class="span2">
              <%= proper_name(field.to_sym) %>
            </td>
            <td class="span10"> 
              <%= simple_format(@patient[field]) %>
            </td>
          <% end %>

        </tr>
      <% end %>
    </body>
  </table>

  <% if current_user.admin? %>
  <%= link_to "Delete Patient", @patient, class: "btn btn-danger", method: :delete, confirm: "Really Delete This Patient Forever?" %>
  <% end %>