config/routes.rb
Surgconf::Application.routes.draw do
  root              to: 'static_pages#home'
  resources         :users
  resources         :patients
  resources         :sessions, only: [:new, :create, :destroy]
  resources         :conferences
  resources         :appearances

  match '/help',    to: 'static_pages#help', via: [:get, :post]
  match '/signup',   to: 'users#new', via: [:get, :post]
  match '/signout',  to: 'sessions#destroy', via: :delete
  match '/signin',   to: 'sessions#new', via: [:get, :post]

end

app/views/layouts/_body.html.haml
-if full_title(yield(:title)).include? 'Home'
  .well.hero-unit.span6
    = yield
-else
  .well.container-fluid
    -flash.each do |key, value|
      .alert{class: "alert-#{key}"} 
        =value
    = yield

app/views/layouts/_footer.html.haml
%footer.span12
  .container-fluid
    %small
      %a{href: "#"} CTS Listing Code
      E. K. Hall
      =show_version
    %nav
      %ul
        %li= link_to "About", "#"
        %li= link_to "Contact", "#"
        %li
          %a{href: "http://www.yale.edu"} Yale

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Ped CTS Listings", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <% if signed_in? %>

            <!-- Conference Menu -->
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Conferences <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "View Conferences", conferences_path, html_options = {class: 'strong'}%></li>
                <li class="divider"></li>
                <% if current_user.editor? %>
                  <li><%= link_to "Create Conference", new_conference_path %></li>
                <% end %>
              </ul>
            </li>
            
            <!-- Patient Menu -->
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Patients <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "View Patients", patients_path %></li>
                <% if current_user.editor? %>
                  <li><%= link_to "Create Patient", new_patient_path %></li>
                <% end %>
                <li class="divider"></li>
              </ul>
            </li>
            
            <!-- Account Menu -->
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "User List", users_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", signout_path, method: "delete" %></li>
              </ul>
            </li>

            <li><span class="label label-warning">Signed In:<%= current_user.name %></span></li>
          <% else %>
            <a class="btn btn-inverse" href=<%= signin_path %> >
              <i class="icon-user icon-white"></i> Sign In</a>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_news.html.haml
%h3 News

%p
  08/03/2012: No current news. Please report all issues with this system to Kevin.

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link(rel='stylesheet'
          href='http://fonts.googleapis.com/css?family=Open+Sans'
          type='text/css')
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container-fluid
      .row-fluid
        = render 'layouts/body'
        
        -if full_title(yield(:title)).include? 'Home'
          .well.span4
            = render 'layouts/news'
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?